### ISSUE TITLE
NaN's in CyAN Previous Prediction Donut

### ISSUE THREAD

**Issue by mathewtitus** [ClearWaterAnalytica/dashboard_or_detroit_lake#6]
Assuming it will be common for dates to be missing their %age bloom stat, let's switch the "NaN" result in the left donut to a simple "-" or "--" to denote the missing data. 

NaN's can be off putting for laypeople! (What does that stand for? Why isn't it a number?)

**Comment by benjiantolin** [comment]
Updated to show "--" if value is "null"
